"""End-to-End integration tests from Webhook to Notifier."""

from unittest.mock import MagicMock, patch
import httpx
import pytest

from pulse.server import app

# ---------------------------------------------------------------------------
# Integration Tests
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_integration_smart_routing():
    """
    Scenario 1: Smart Routing & Formatted Delivery
    A valid entityCreated event with a mapped owner correctly routes to their channel.
    """
    payload = {
        "eventType": "entityCreated",
        "entityType": "table",
        "entityFullyQualifiedName": "sample.orders",
        "entity": {
            "owner": {"name": "nishanthatgit"}
        }
    }
    
    mock_client = MagicMock()
    mock_client.chat_postMessage = MagicMock()

    with patch("pulse.notifier._get_slack_client", return_value=mock_client), \
         patch("pulse.notifier.settings") as mock_settings:
        
        mock_settings.slack_bot_token = "xoxb-test"
        mock_settings.slack_default_channel = "#default-channel"
        mock_settings.om_server_url = "http://localhost:8585"

        async with httpx.AsyncClient(transport=httpx.ASGITransport(app=app), base_url="http://test") as client:
            resp = await client.post("/webhook", json=payload)
            
    assert resp.status_code == 200
    assert resp.json() == {"status": "ok"}
    
    # Verify Slack was called exactly once
    mock_client.chat_postMessage.assert_called_once()
    
    # Verify channel was routed to the mapped owner channel (from OWNER_SLACK_MAP)
    call_kwargs = mock_client.chat_postMessage.call_args.kwargs
    assert call_kwargs["channel"] == "#data-engineering"
    assert "blocks" in call_kwargs
    assert len(call_kwargs["blocks"]) > 0


@pytest.mark.asyncio
async def test_integration_default_routing():
    """
    Scenario 2: Default Routing
    A valid event without an owner is routed to the default channel.
    """
    payload = {
        "eventType": "entityUpdated",
        "entityType": "topic",
        "entityFullyQualifiedName": "kafka.events",
    }
    
    mock_client = MagicMock()
    mock_client.chat_postMessage = MagicMock()

    with patch("pulse.notifier._get_slack_client", return_value=mock_client), \
         patch("pulse.notifier.settings") as mock_settings:
        
        mock_settings.slack_bot_token = "xoxb-test"
        mock_settings.slack_default_channel = "#default-channel"
        mock_settings.om_server_url = "http://localhost:8585"

        async with httpx.AsyncClient(transport=httpx.ASGITransport(app=app), base_url="http://test") as client:
            resp = await client.post("/webhook", json=payload)
            
    assert resp.status_code == 200
    assert resp.json() == {"status": "ok"}
    
    mock_client.chat_postMessage.assert_called_once()
    call_kwargs = mock_client.chat_postMessage.call_args.kwargs
    assert call_kwargs["channel"] == "#default-channel"
    assert "blocks" in call_kwargs


@pytest.mark.asyncio
async def test_integration_filtered_payload():
    """
    Scenario 3: Filtered Payload Drop
    An event generated by the ingestion-bot is filtered out before Slack delivery.
    """
    payload = {
        "eventType": "entityCreated",
        "entityType": "table",
        "entityFullyQualifiedName": "sample.orders",
        "updatedBy": "ingestion-bot",
    }
    
    mock_client = MagicMock()
    mock_client.chat_postMessage = MagicMock()

    with patch("pulse.notifier._get_slack_client", return_value=mock_client), \
         patch("pulse.notifier.settings") as mock_settings:
        
        mock_settings.slack_bot_token = "xoxb-test"
        mock_settings.slack_default_channel = "#default-channel"
        mock_settings.om_server_url = "http://localhost:8585"

        async with httpx.AsyncClient(transport=httpx.ASGITransport(app=app), base_url="http://test") as client:
            resp = await client.post("/webhook", json=payload)
            
    # API still returns 200, but ignores the event internally
    assert resp.status_code == 200
    assert resp.json() == {"status": "ignored"}
    
    # Ensure Slack is NEVER called
    mock_client.chat_postMessage.assert_not_called()
